In [2]:
import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [63]:
type(a)

numpy.ndarray

In [64]:
len(a)

5

In [65]:
a[1]  #indexing

2

In [68]:
#for printing array from start to end
a[0:]

array([1, 2, 3, 4, 5])

In [69]:
a.mean()  #finding the mean

3.0

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.empty(2)

array([1., 1.])

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [20]:
np.arange(1,20,3) #first num, second num, gap

array([ 1,  4,  7, 10, 13, 16, 19])

In [31]:
np.linspace(1,20,num=5, dtype=np.int32) #first num, second num, how many number you want in this range, the type in mupy is float but we can specify it 

array([ 1,  5, 10, 15, 20])

In [32]:
c = np.array([2,5,7,0,7,4,3])
c

array([2, 5, 7, 0, 7, 4, 3])

In [35]:
np.sort(c)   #sort out the data

array([0, 2, 3, 4, 5, 7, 7])

In [38]:
d= np.array([1,2,3,4,5,6,7])
d

array([1, 2, 3, 4, 5, 6, 7])

In [44]:
d.ndim

1

In [41]:
np.concatenate((c,a))     #merging the arrays

array([0, 2, 3, 4, 5, 7, 7, 1, 2, 3, 4, 5])

In [49]:
e = np.array([[1,2,3,7],
             [4,5,6,9],
             [7,8,9,0]])
e

array([[1, 2, 3, 7],
       [4, 5, 6, 9],
       [7, 8, 9, 0]])

In [50]:
e.ndim

2

In [51]:
e.size

12

In [52]:
e.shape

(3, 4)

## 2D ARRAY

In [57]:
np.ones((3,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [59]:
np.empty((2,3), dtype=np.int32)

array([[         0, 1072693248,          0],
       [1072693248,          0, 1072693248]])

In [74]:
f= np.array([[1,2,3,4,5],[6,7,8,9,0]])
f


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [79]:
g= np.array([[42,45,89,56,2],[85,72,18,23,5]])
g

array([[42, 45, 89, 56,  2],
       [85, 72, 18, 23,  5]])

In [80]:
np.concatenate((f,g))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [42, 45, 89, 56,  2],
       [85, 72, 18, 23,  5]])

In [81]:
np.concatenate((f,g), axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [42, 45, 89, 56,  2],
       [85, 72, 18, 23,  5]])

In [84]:
np.concatenate((f,g), axis=1)

array([[ 1,  2,  3,  4,  5, 42, 45, 89, 56,  2],
       [ 6,  7,  8,  9,  0, 85, 72, 18, 23,  5]])

## 3D ARRAY

In [85]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [86]:
np.arange(24).reshape(2,3,4)  #trick24=2*3*4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [87]:
#converting 1d to 2d
h= np.array([1,2,3,4,5,6,7,8,9])
h

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
k = h[np.newaxis, : ].reshape(3,3)
k

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])